### ISSUE TITLE
Bug report on ASSISTments2015 Data Analysis

### ISSUE THREAD

**Issue by gguu1314** [bigdata-ustc/EduData#44]
### 1. Pie chart of "percent of correct answers"

Your code and chart are as follows.

```Python
ds = data['correct'].value_counts().reset_index()

ds.columns = [
    'correct',
    'percent'
]

ds['percent'] /= len(data)
ds = ds.sort_values(['percent'])

fig = px.pie(
    ds,
    names=['0', '1/10', '1/5', '1/4', '1/3', '1/2', '2/3', '3/4', '4/5', '9/10', '1'],
    values='percent',
    title='Percent of correct answers'
)

fig.show("svg")
```

<br/>
<br/>

![图片](https://user-images.githubusercontent.com/88154940/127594555-ddf5f6ed-d64d-4bec-827d-564edaf48b0c.png)

If we print out ds before showing the chart:

```python
print(ds)
```

we can see the correct connection between "correct" and "percent" in this table:

```
     correct   percent
10  0.100000  0.000001
8   0.800000  0.000003
9   0.200000  0.000003
7   0.900000  0.000004
6   0.250000  0.000106
5   0.500000  0.000143
4   0.750000  0.000398
3   0.333333  0.011830
2   0.666667  0.022552
1   0.000000  0.258840
0   1.000000  0.706121
```

Comparing the table and the pie chart, we can see that the chart can not reflect the connection between "correct" and "percent" correctly.

To solve this bug, we can change:

```python
ds = ds.sort_values(['percent'])
```

into:

```python
ds = ds.sort_values(['correct'])
```

Then we can get the correct pie chart:

![newplot](https://user-images.githubusercontent.com/88154940/127601339-e5029099-3c8a-4eb6-9171-7275262795b8.png)

<br/>

### 2. fig.show("svg")

When I use:

```python
fig.show(“svg”)
```

it casue an error,and the error message is:

```
plotlyjs argument is not a valid URL or file path
```

I don't know why.

But if I use:

```python
fig.show()
```

it won't cause an error.

The declaration of show( ) is:

```python
show(self, args, kwargs)
```

How to solve this?

**Comment by fannazya** [comment]
Hi@gguu1314 , thank you for your interest in EduData and for reporting this issue. The first error about the Pie chart will be fixed. For the second bug, it might be related to your installation of plotly, and of course you can also show figures using 'fig.show()'.

**Comment by gguu1314** [comment]
Thank you for your reply!

在2021-10-15 ***@***.***写道：

***@***.*** , thank you for your interest in EduData and for reporting this issue. The first error about the Pie chart will be fixed. For the second bug, it might be related to your installation of plotly, and of course you can also show figures using 'fig.show()'.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
